name: pull request workflow for native tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
      
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      
      - name: Start ChromeDriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      
      - name: Build with Maven
        run: mvn clean compile
      
      - name: Run login Tests
        run: mvn test -Dtest=LoginScenarios

      - name: Run purchase Tests
        run: mvn test -Dtest=PurchaseScenarios

      - name: Run cucumber Tests
        run: mvn test -Dtest=CucumberTestRunner
      
